# **Q3) Consider the given breast cancer dataset from the given google drive link, the last column has the target variable (2 classes: "B" for benign and "M" for malignant) and the remaining columns have the features.**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_raw=pd.read_csv("/content/drive/Othercomputers/My Laptop/3-2/Data Mining/assignments/assignment 2/wdbc.data",header=None)
display(data_raw)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,879830,M,17.01,20.26,109.70,904.3,0.08772,0.07304,0.06950,0.05390,...,19.80,25.05,130.00,1210.0,0.1111,0.1486,0.1932,0.10960,0.3275,0.06469
208,8810158,B,13.11,22.54,87.02,529.4,0.10020,0.14830,0.08705,0.05102,...,14.55,29.16,99.48,639.3,0.1349,0.4402,0.3162,0.11260,0.4128,0.10760
209,8810436,B,15.27,12.91,98.17,725.5,0.08182,0.06230,0.05892,0.03157,...,17.38,15.92,113.70,932.7,0.1222,0.2186,0.2962,0.10350,0.2320,0.07474
210,881046502,M,20.58,22.14,134.70,1290.0,0.09090,0.13480,0.16400,0.09561,...,23.24,27.84,158.30,1656.0,0.1178,0.2920,0.3861,0.19200,0.2909,0.05865
211,8810528,B,11.84,18.94,75.51,428.0,0.08871,0.06900,0.02669,0.01393,...,13.30,24.99,85.22,546.3,0.1280,0.1880,0.1471,0.06913,0.2535,0.07993

In [ ]:
data_raw.columns=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF']
print(data_raw)

             A  B      C      D       E       F        G        H        I  \
0       842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010
1       842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690
2     84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740
3     84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140
4     84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800
..         ... ..    ...    ...     ...     ...      ...      ...      ...
207     879830  M  17.01  20.26  109.70   904.3  0.08772  0.07304  0.06950
208    8810158  B  13.11  22.54   87.02   529.4  0.10020  0.14830  0.08705
209    8810436  B  15.27  12.91   98.17   725.5  0.08182  0.06230  0.05892
210  881046502  M  20.58  22.14  134.70  1290.0  0.09090  0.13480  0.16400
211    8810528  B  11.84  18.94   75.51   428.0  0.08871  0.06900  0.02669

           J  ...      W      X       Y       Z      AA      AB      AC  \
0    0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119
1    0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416
2    0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504
3    0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869
4    0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000
..       ...  ...    ...    ...     ...     ...     ...     ...     ...
207  0.05390  ...  19.80  25.05  130.00  1210.0  0.1111  0.1486  0.1932
208  0.05102  ...  14.55  29.16   99.48   639.3  0.1349  0.4402  0.3162
209  0.03157  ...  17.38  15.92  113.70   932.7  0.1222  0.2186  0.2962
210  0.09561  ...  23.24  27.84  158.30  1656.0  0.1178  0.2920  0.3861
211  0.01393  ...  13.30  24.99   85.22   546.3  0.1280  0.1880  0.1471

          AD      AE       AF
0    0.26540  0.4601  0.11890
1    0.18600  0.2750  0.08902
2    0.24300  0.3613  0.08758
3    0.25750  0.6638  0.17300
4    0.16250  0.2364  0.07678
..       ...     ...      ...
207  0.10960  0.3275  0.06469
208  0.11260  0.4128  0.10760
209  0.10350  0.2320  0.07474
210  0.19200  0.2909  0.05865
211  0.06913  0.2535  0.07993

[212 rows x 32 columns]

In [ ]:
data_raw.describe()

,A,C,D,E,F,G,H,I,J,K,...,W,X,Y,Z,AA,AB,AC,AD,AE,AF
count,2.120000e+02,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,...,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000,212.000000
mean,2.310710e+07,14.342910,19.005896,93.726557,673.113208,0.099898,0.115448,0.104076,0.056553,0.187020,...,16.785061,25.645094,110.943585,931.369811,0.137937,0.288787,0.314467,0.128404,0.307262,0.087653
std,1.054031e+08,3.514826,3.765864,24.305410,342.298054,0.014021,0.058114,0.085413,0.040013,0.030163,...,4.790650,5.828196,33.658412,544.000004,0.023743,0.181997,0.224852,0.068148,0.075289,0.021339
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.062510,0.019380,0.000000,0.000000,0.116700,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.575872e+05,11.922500,16.285000,77.152500,438.350000,0.090432,0.071912,0.036950,0.025957,0.168100,...,13.315000,21.375000,86.037500,544.925000,0.122275,0.167300,0.139850,0.072740,0.259150,0.073640
50%,8.666940e+05,13.625000,19.300000,88.085000,575.250000,0.098510,0.103250,0.086575,0.051855,0.183800,...,15.910000,25.830000,106.050000,767.900000,0.138500,0.233700,0.274550,0.123900,0.293250,0.082640
75%,8.510901e+06,16.235000,21.740000,108.175000,821.500000,0.109125,0.148350,0.147075,0.081600,0.199500,...,20.020000,29.985000,130.075000,1234.500000,0.152625,0.390325,0.450400,0.178500,0.343875,0.097745
max,8.810465e+08,27.220000,27.540000,182.100000,2250.000000,0.144700,0.345400,0.426800,0.201200,0.304000,...,33.120000,41.850000,220.800000,3216.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [ ]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       212 non-null    int64
 1   B       212 non-null    object
 2   C       212 non-null    float64
 3   D       212 non-null    float64
 4   E       212 non-null    float64
 5   F       212 non-null    float64
 6   G       212 non-null    float64
 7   H       212 non-null    float64
 8   I       212 non-null    float64
 9   J       212 non-null    float64
 10  K       212 non-null    float64
 11  L       212 non-null    float64
 12  M       212 non-null    float64
 13  N       212 non-null    float64
 14  O       212 non-null    float64
 15  P       212 non-null    float64
 16  Q       212 non-null    float64
 17  R       212 non-null    float64
 18  S       212 non-null    float64
 19  T       212 non-null    float64
 20  U       212 non-null    float64
 21  V       212 non-null    float64
 22  W       212 non-null    float64
 23  X       212 non-null    float64
 24  Y       212 non-null    float64
 25  Z       212 non-null    float64
 26  AA      212 non-null    float64
 27  AB      212 non-null    float64
 28  AC      212 non-null    float64
 29  AD      212 non-null    float64
 30  AE      212 non-null    float64
 31  AF      212 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 53.1+ KB

In [ ]:
data_raw.isnull().any()

A     False
B     False
C     False
D     False
E     False
F     False
G     False
H     False
I     False
J     False
K     False
L     False
M     False
N     False
O     False
P     False
Q     False
R     False
S     False
T     False
U     False
V     False
W     False
X     False
Y     False
Z     False
AA    False
AB    False
AC    False
AD    False
AE    False
AF    False
dtype: bool

In [ ]:
data_raw_backup=data_raw.copy()
Y=data_raw['B']
X=data_raw.drop('B',axis=1,inplace=True)
#print(X)
#print(Y)
Y.replace({'B':0,'M':1},inplace=True)
data_raw['Result']=Y
print(data_raw)
#print(Y)

             A      C      D       E       F        G        H        I  \
0       842302  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010
1       842517  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690
2     84300903  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740
3     84348301  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140
4     84358402  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800
..         ...    ...    ...     ...     ...      ...      ...      ...
207     879830  17.01  20.26  109.70   904.3  0.08772  0.07304  0.06950
208    8810158  13.11  22.54   87.02   529.4  0.10020  0.14830  0.08705
209    8810436  15.27  12.91   98.17   725.5  0.08182  0.06230  0.05892
210  881046502  20.58  22.14  134.70  1290.0  0.09090  0.13480  0.16400
211    8810528  11.84  18.94   75.51   428.0  0.08871  0.06900  0.02669

           J       K  ...      X       Y       Z      AA      AB      AC  \
0    0.14710  0.2419  ...  17.33  184.60  2019.0  0.1622  0.6656  0.7119
1    0.07017  0.1812  ...  23.41  158.80  1956.0  0.1238  0.1866  0.2416
2    0.12790  0.2069  ...  25.53  152.50  1709.0  0.1444  0.4245  0.4504
3    0.10520  0.2597  ...  26.50   98.87   567.7  0.2098  0.8663  0.6869
4    0.10430  0.1809  ...  16.67  152.20  1575.0  0.1374  0.2050  0.4000
..       ...     ...  ...    ...     ...     ...     ...     ...     ...
207  0.05390  0.2026  ...  25.05  130.00  1210.0  0.1111  0.1486  0.1932
208  0.05102  0.1850  ...  29.16   99.48   639.3  0.1349  0.4402  0.3162
209  0.03157  0.1359  ...  15.92  113.70   932.7  0.1222  0.2186  0.2962
210  0.09561  0.1765  ...  27.84  158.30  1656.0  0.1178  0.2920  0.3861
211  0.01393  0.1533  ...  24.99   85.22   546.3  0.1280  0.1880  0.1471

          AD      AE       AF  Result
0    0.26540  0.4601  0.11890       1
1    0.18600  0.2750  0.08902       1
2    0.24300  0.3613  0.08758       1
3    0.25750  0.6638  0.17300       1
4    0.16250  0.2364  0.07678       1
..       ...     ...      ...     ...
207  0.10960  0.3275  0.06469       1
208  0.11260  0.4128  0.10760       0
209  0.10350  0.2320  0.07474       0
210  0.19200  0.2909  0.05865       1
211  0.06913  0.2535  0.07993       0

[212 rows x 32 columns]

In [ ]:
X = data_raw.iloc[:, :-1].values
Y = data_raw.iloc[:, -1].values.reshape(-1,1)
#print(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.3, random_state=747192)

In [ ]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
        ''' constructor ''' 
        
        # for decision node
        self.left = left
        self.right = right
        self.info_gain = info_gain
        self.feature_index = feature_index
        self.threshold = threshold        
        # for leaf node
        self.value = value

In [ ]:
class DTC():
    def __init__(self, min_samples_split=2, max_depth=2):
        ''' constructor '''
        self.root = None
        # stopping conditions
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        ''' recursive function to build the tree ''' 
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        num_samples, num_features = np.shape(X)
        
        # split until stopping conditions are met
        if num_samples>=self.min_samples_split and curr_depth<=self.max_depth:
            # find the best split
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # check if information gain is positive
            if best_split["info_gain"]>0:
                # recur left
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # recur right
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # return decision node
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["info_gain"])
        
        # compute leaf node
        leaf_value = self.calculate_leaf_value(Y)
        # return leaf node
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
        ''' function to find the best split '''
        best_split = {}
        max_info_gain = -float("inf")
        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)
            
            for threshold in possible_thresholds:
                
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # compute information gain
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    
                    if curr_info_gain>max_info_gain:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["info_gain"] = curr_info_gain
                        max_info_gain = curr_info_gain
                        
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        ''' function to split the data '''
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        ''' function to compute information gain '''
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        if mode=="gini":
            gain = self.gini_index(parent) - (weight_l*self.gini_index(l_child) + weight_r*self.gini_index(r_child))
        else:
            gain = self.entropy(parent) - (weight_l*self.entropy(l_child) + weight_r*self.entropy(r_child))
        return gain
    
    def entropy(self, y):
        ''' function to compute entropy '''
        
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy
    
    def gini_index(self, y):
        ''' function to compute gini index '''
        
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini
        
    def calculate_leaf_value(self, Y):
        ''' function to compute leaf node '''
        
        Y = list(Y)
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        ''' function to print the tree '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("X_"+str(tree.feature_index), "<=", tree.threshold, "?", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        ''' function to train the tree '''
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
    
    def predict(self, X):
        ''' function to predict new dataset '''
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def make_prediction(self, x, tree):
        ''' function to predict a single data point '''
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

In [ ]:
classified_data = DTC(min_samples_split=2, max_depth=1000)
classified_data.fit(X_train,Y_train)
classified_data.print_tree()

X_24 <= 711.2 ? 0.3308594011296715
 left:X_9 <= 0.2403 ? 0.05229291716686661
  left:X_2 <= 22.3 ? 0.03748558246828153
    left:0.0
    right:X_0 <= 868202.0 ? 0.4444444444444444
        left:1.0
        right:0.0
  right:1.0
 right:X_28 <= 0.1035 ? 0.08286763094455393
  left:X_0 <= 845636.0 ? 0.2777777777777777
    left:1.0
    right:0.0
  right:X_22 <= 19.85 ? 0.06751543209876548
    left:X_3 <= 102.0 ? 0.49382716049382713
        left:0.0
        right:1.0
    right:1.0

In [ ]:
Y_pred = classified_data.predict(X_test) 
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.890625

Hence we can see here that for the random state 747192 we get accuracy of our model as 89.06225 % for 70 30 percent of data split